[package]
name = "Comet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
chrono = "0.4.38"
colored = "2.1.0"
dirs-next = "2.0.0"
indicatif = "0.17.9"
serde = { version = "1.0.215", features = ["derive"] }
sysinfo = "0.32.0"
tempfile = "3.14.0"
thiserror = "2.0.3"
toml = "0.8.19"
