[workspace]

resolver = "2"
members = [
    "cli",
    "server"
]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
opt-level = "z"  # or "s" for smaller binaries
strip = true

[workspace.dependencies]
anyhow = "1.0.93"
dirs-next = "2.0.0"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
thiserror = "2.0.3"